export const groups = [
  {
    id: 'hukuk-mali',
    title: 'Hukuk ve Mali Düzen',
    summary: 'Hukuk · Mali Müşavirlik · YMM · Patent · Finansal Danışmanlık',
  },
  {
    id: 'gayrimenkul',
    title: 'Gayrimenkul ve Büyüme',
    summary: 'Türkiye & Kıbrıs Franchise · Project · X Real Estate · Master Franchise · Sanal Ofis',
  },
  {
    id: 'maliyet-varlik',
    title: 'Maliyet ve Varlık Yönetimi',
    summary: 'Elektrik Danışmanlığı · Elektrik · Enerji · Sigorta · Auto · Barter · Varlık Yönetimi',
  },
  {
    id: 'teknoloji',
    title: 'Teknoloji ve Gelişim',
    summary: 'Fair · Software · Yapay Zekâ · Call Center · Sosyal Medya · Architecture · Şehir Planlama',
  },
];

export const steps = [
  'İhtiyacı anlarız',
  'Uzmanlıkları birleştiririz',
  'Yol haritasını kurarız',
  'Süreci izleriz',
];

export const services = [
  {
    no: '01',
    group: 'hukuk-mali',
    kicker: 'Hukuk ve Uyum',
    name: 'XRE Hukuk',
    headline: 'Her aşamada hukuki destek.',
    intro:
      'Şirketlerin ve bireylerin hukuki ihtiyaçlarını, ilgili alanda çalışan avukatlarla ele alan bütüncül bir hizmet yaklaşımı. Önleyici danışmanlıktan uyuşmazlıkların çözümüne kadar süreçlerin koordinasyonu.',
    items: [
      ['Şirketler ve ticaret', 'Şirket kuruluşu, ortaklık ilişkileri, yönetim kararları, birleşme ve devralmalar; ticari sözleşmeler ve rekabet hukuku.'],
      ['Alacak ve yeniden yapılanma', 'İcra ve iflas, ticari alacakların takibi, temlik, borç yapılandırma, konkordato ve alacaklı görüşmeleri.'],
      ['Gayrimenkul ve inşaat', 'Tapu ve mülkiyet, kira, kat mülkiyeti, imar, kamulaştırma, inşaat ve gayrimenkul geliştirme sözleşmeleri.'],
      ['Çalışma, vergi ve idare', 'İş ve sosyal güvenlik hukuku, işveren süreçleri, vergi uyuşmazlıkları, idari işlemler ve kamu ihale hukuku.'],
      ['Bireysel haklar ve sorumluluk', 'Ceza, aile, miras, tüketici, sigorta, sağlık ve tazminat hukuku; kişisel hakların korunması.'],
      ['Dijital ve uluslararası alan', 'Bilişim, KVKK, fikrî ve sınai haklar, yabancılar ve vatandaşlık; uluslararası işlemler, arabuluculuk ve tahkim.'],
    ],
    highlight: 'Hukuki ihtiyacı erken belirleyen, süreçleri düzenli izleyen bir çalışma modeli.',
    cta: 'Hukuki ihtiyacınızı birlikte değerlendirelim.',
    note: 'Avukatlık hizmetleri, ilgili baroya kayıtlı avukatlar tarafından mesleki bağımsızlık ve yetki sınırları içinde yürütülür.',
  },
  {
    no: '02',
    group: 'gayrimenkul',
    kicker: 'Franchise ve Büyüme',
    name: 'XRE Türkiye & Kıbrıs',
    headline: 'Kendi ofisiniz. Ortak bir marka.',
    intro:
      'Türkiye ve Kıbrıs’ta gayrimenkul ofisi kurmak veya mevcut ofisini XRE çatısı altında büyütmek isteyen girişimciler için franchise yapılanması. Marka, eğitim, teknoloji ve operasyon aynı çalışma düzeninde buluşur.',
    items: [
      ['Bölge ve ofis planlaması', 'Hedef bölge, yerel pazar, lokasyon ve ofis modeli değerlendirilir. İş planı ile açılış adımları birlikte oluşturulur.'],
      ['Marka ve kurumsal kimlik', 'Ofis görünümü, iletişim dili ve pazarlama materyalleri için ortak standartlar; kurumsal tanıtım desteği.'],
      ['Eğitim ve teknoloji', 'Danışman gelişimi, satış ve portföy yönetimi eğitimleri; CRM, müşteri takibi ve dijital çalışma süreçleri.'],
      ['Operasyon ve gelişim', 'Ekip kurma, danışman kazanımı, performans takibi, portföy iş birliği ve sürdürülebilir ofis yönetimi.'],
    ],
    stat: ['2', 'Türkiye ve Kıbrıs'],
    highlight: 'Yerel girişimcilik gücünü XRE’nin iş ağı ve çalışma sistemiyle birleştirin.',
    cta: 'Türkiye veya Kıbrıs franchise başvurunuzu iletin.',
    note: 'Bölge, kullanım hakları, bedeller ve destek kapsamı ilgili franchise sözleşmesinde belirlenir.',
  },
  {
    no: '03',
    group: 'gayrimenkul',
    kicker: 'Uluslararası Gayrimenkul',
    name: 'XRE Project',
    headline: '15 ülkede projelerle buluşun.',
    intro:
      '15 ülkedeki proje seçeneklerini tek bir danışmanlık sürecinde değerlendirin. Yaşam, iş veya gayrimenkul edinimi amacınıza uygun alternatifleri bütçeniz, ödeme planınız ve kullanım beklentinizle birlikte ele alıyoruz.',
    items: [
      ['Proje seçenekleri', 'Konut, rezidans, villa, ofis, ticari ünite ve karma yaşam projeleri; portföydeki güncel seçeneklerin sunumu.'],
      ['İhtiyaca uygun eşleştirme', 'Ülke ve lokasyon tercihi, bütçe, kullanım amacı, teslim dönemi ve ödeme planına göre alternatif oluşturma.'],
      ['Karşılaştırmalı değerlendirme', 'Proje özellikleri, geliştirici bilgileri, sözleşme koşulları, mülkiyet yapısı ve işlem maliyetlerinin incelenmesi.'],
      ['Satış süreci koordinasyonu', 'Online sunum, proje ziyareti, rezervasyon, sözleşme, ödeme takibi ve teslim aşamalarında koordinasyon.'],
    ],
    stat: ['15', 'ülkede proje seçenekleri'],
    highlight: 'Uluslararası proje seçeneklerini anlaşılır bilgilerle karşılaştırın.',
    cta: 'Bütçenize ve hedef ülkenize uygun proje sunumu isteyin.',
    note: 'Portföy ve koşullar güncellenebilir. Mülkiyet, vergi ve ikamet şartları ülkeye göre değerlendirilir; getiri taahhüdü verilmez.',
  },
  {
    no: '04',
    group: 'gayrimenkul',
    kicker: 'Türkiye Genelinde Gayrimenkul',
    name: 'XRE X Real Estate',
    headline: 'Alım. Satım. Kiralama.',
    intro:
      'Türkiye çapında bireysel ve kurumsal gayrimenkul ihtiyaçları için alım, satım ve kiralama danışmanlığı. Taşınmazın niteliğine ve hedef kitlesine uygun pazarlama, görüşme ve işlem takibi.',
    items: [
      ['Konut ve yaşam', 'Daire, müstakil ev, villa, rezidans, yazlık, bağ evi ve çiftlik evi; satılık ve kiralık konut seçenekleri.'],
      ['Ticari gayrimenkul', 'Ofis, büro, dükkân, mağaza, plaza, iş merkezi, AVM ve ticari üniteler; şirketlere yer seçimi desteği.'],
      ['Sanayi ve özel kullanım', 'Fabrika, atölye, depo, lojistik tesis, otel, turistik tesis ve akaryakıt istasyonu gibi özel nitelikli taşınmazlar.'],
      ['Arsa ve arazi', 'Konut ve ticaret imarlı arsalar, sanayi arsaları, tarla, bağ, bahçe ve geliştirmeye konu araziler.'],
    ],
    stat: ['TR', 'Türkiye çapında hizmet'],
    highlight: 'Taşınmazınıza uygun alıcıyı, kiracıyı veya yeni adresinizi birlikte bulun.',
    cta: 'Gayrimenkulünüzü veya arayışınızı bizimle paylaşın.',
    note: 'İşlemler ilgili yetki belgeleri, mevzuat ve taşınmazın hukuki durumu çerçevesinde yürütülür.',
  },
  {
    no: '05',
    group: 'maliyet-varlik',
    kicker: 'Fatura ve Tüketim Kontrolü',
    name: 'XRE Elektrik Danışmanlığı',
    headline: 'Faturanızı anlayın. Maliyetinizi yönetin.',
    intro:
      'Yüksek elektrik faturası ödeyen işletmeler için fatura kontrolü, tarife ve sözleşme incelemesi, tüketim analizi ve düzenli raporlama. İşletmenizin tüketim yapısına göre maliyetleri ve iyileştirme fırsatlarını değerlendiriyoruz.',
    items: [
      ['Fatura doğruluk kontrolü', 'Tüketim, birim fiyat, endeks, dönem ve fatura kalemlerinin kontrolü; sözleşme ile tahakkukun karşılaştırılması.'],
      ['Tarife ve sözleşme analizi', 'Abone grubu, tarife yapısı, fiyatlama yöntemi, sözleşme süresi ve fesih koşullarının değerlendirilmesi.'],
      ['Teknik maliyet incelemesi', 'Reaktif enerji, güç aşımı ve kompanzasyon kaynaklı kalemlerin analizi; gerekli teknik incelemeye yönlendirme.'],
      ['Takip ve iyileştirme', 'Dönemsel tüketim karşılaştırması, sapmaların raporlanması; hatalı tahakkuklarda başvuru ve düzeltme takibi.'],
    ],
    highlight: 'Tasarruf fırsatlarını tahminle değil, fatura ve tüketim verileriyle belirleyin.',
    cta: 'Son elektrik faturalarınızla inceleme talebi oluşturun.',
    note: 'Tasarruf ve düzeltme imkânı inceleme sonucuna bağlıdır. Teknik müdahaleler yetkili uzmanlarca yapılır.',
  },
  {
    no: '06',
    group: 'maliyet-varlik',
    kicker: 'Türkiye Çapında Elektrik Tedariki',
    name: 'XRE Elektrik',
    headline: 'İşletmenize özel elektrik teklifi.',
    intro:
      'Türkiye genelinde uygun tüketicileri indirimli elektrik tedarik seçenekleriyle buluşturuyoruz. Mevcut tüketim profilinizi ve sözleşmenizi inceleyerek lisanslı tedarikçiler üzerinden karşılaştırılabilir teklifler oluşturuyoruz.',
    items: [
      ['Kimler için?', 'Fabrikalar, oteller, marketler, restoranlar, özel sağlık ve eğitim kurumları, depolar ve çok şubeli işletmeler.'],
      ['Tüketim profiline uygun teklif', 'Tüketim miktarı ve zaman dağılımı değerlendirilir; fiyatlama yapısı ile sözleşme koşulları birlikte sunulur.'],
      ['Tedarik geçişi koordinasyonu', 'Uygunluk ve mevcut taahhüt kontrolü, belge hazırlığı, sözleşme ve tedarik başlangıcının takibi.'],
      ['Düzenli maliyet takibi', 'İlk fatura kontrolü, dönemsel karşılaştırmalar ve yenileme dönemi değerlendirmesiyle sürecin izlenmesi.'],
    ],
    highlight: 'Elektrik alımınızı işletmenizin maliyet yönetiminin bir parçası hâline getirin.',
    cta: 'Faturanızı paylaşın, size özel tedarik teklifini hazırlayalım.',
    note: 'İndirim; tüketim, piyasa ve sözleşme koşullarına bağlıdır. Elektrik tedariki lisanslı tedarik şirketleri tarafından sağlanır.',
  },
  {
    no: '07',
    group: 'maliyet-varlik',
    kicker: 'Fizibiliteden Devreye Almaya',
    name: 'XRE Enerji | Santral Kurulumu',
    headline: 'Enerji projenizi birlikte hayata geçirelim.',
    intro:
      'Şirketlerin ihtiyacına uygun enerji santrali projelerinde fizibilite, mühendislik ve kurulum koordinasyonu. Enerji kaynağı, teknoloji, saha, tüketim ve bağlantı koşullarını birlikte değerlendirerek proje yol haritasını oluşturuyoruz.',
    items: [
      ['Ön fizibilite ve saha analizi', 'Enerji kaynağı, tüketim ihtiyacı, saha ve teknoloji uygunluğu, bağlantı imkânı ve yatırım bütçesinin değerlendirilmesi.'],
      ['Proje ve izin koordinasyonu', 'Mühendislik projeleri, ilgili kurum başvuruları, izin ve bağlantı süreçleri; yetkili uzmanlarla dosya ve takvim takibi.'],
      ['Tedarik ve kurulum', 'Ekipman seçimi, teklif karşılaştırması, yüklenici koordinasyonu, montaj ve saha çalışmalarının proje kapsamında izlenmesi.'],
      ['Devreye alma ve işletme', 'Test, kabul ve devreye alma koordinasyonu; performans izleme, bakım planı ve işletme dönemine geçiş desteği.'],
    ],
    highlight: 'Enerji projesini teknik uygunluk, yatırım maliyeti ve işletme ihtiyaçlarıyla birlikte planlayın.',
    cta: 'Kurulum için konum ve tüketim bilgilerinizi paylaşın.',
    note: 'Mühendislik ve uygulama işleri yetkili kuruluşlarca yürütülür. Bağlantı, izin, üretim ve geri dönüş süresi garanti edilmez.',
  },
  {
    no: '08',
    group: 'maliyet-varlik',
    kicker: 'Enerji Santrali ve Proje Alım-Satımı',
    name: 'XRE Enerji | Enerji Santralleri Satışı',
    headline: 'Enerji varlıklarını verileriyle değerlendirin.',
    intro:
      'Güneş, rüzgâr, hidroelektrik, jeotermal, biyokütle, biyogaz ve diğer enerji santrallerinde alım-satım danışmanlığı. Kurulu tesisleri ve proje aşamasındaki seçenekleri teknik, hukuki ve mali koşullarıyla birlikte değerlendiriyoruz.',
    items: [
      ['Santral ve proje eşleştirme', 'Enerji kaynağı, konum, kurulu güç, işletme durumu, bütçe ve edinim modeline göre uygun santral ve proje seçenekleri.'],
      ['Teknik ve işletmesel inceleme', 'Üretim geçmişi veya üretim varsayımları, kaynak ve ekipman durumu, bakım kayıtları, performans ve işletme giderlerinin incelenmesi.'],
      ['Hukuki ve mali değerlendirme', 'Mülkiyet veya kullanım hakları, izin ve lisanslar, bağlantı ve satış sözleşmeleri, borçlar ve devir koşullarının değerlendirilmesi.'],
      ['Tekliften devir aşamasına', 'Gizlilik, veri paylaşımı, teklif, müzakere, sözleşme ve devir adımlarının koordinasyonu; uzman ekipler arası süreç takibi.'],
    ],
    highlight: 'Santral kararınızı üretim verileri, kaynak koşulları ve işlem yapısıyla birlikte değerlendirin.',
    cta: 'Satmak veya almak istediğiniz enerji santralinin bilgilerini paylaşın.',
    note: 'Santral, proje veya şirket payı devri ilgili izin ve sözleşmelere bağlıdır. Üretim, gelir veya getiri taahhüdü verilmez.',
  },
  {
    no: '09',
    group: 'maliyet-varlik',
    kicker: 'Bireysel ve Kurumsal Güvence',
    name: 'XRE Sigorta',
    headline: 'Doğru teminat. Düzenli takip.',
    intro:
      'Aracınızdan iş yerinize, sağlığınızdan ticari faaliyetlerinize kadar sigorta ihtiyaçlarınızı birlikte belirliyoruz. Teklifleri yalnızca fiyatla değil; teminat, limit, muafiyet ve hasar süreciyle birlikte değerlendiriyoruz.',
    items: [
      ['Araç ve seyahat', 'Zorunlu trafik, kasko ve seyahat sağlık sigortası; kişisel ve kurumsal araç ihtiyaçlarına uygun seçenekler.'],
      ['Sağlık ve yaşam', 'Tamamlayıcı ve özel sağlık sigortası, ferdi kaza ve ihtiyaca göre hayat sigortası seçenekleri.'],
      ['Konut ve iş yeri', 'DASK, konut, iş yeri, yangın ve ilgili ek teminatlar; taşınmaz, eşya ve faaliyet risklerinin değerlendirilmesi.'],
      ['Teminat ve kurumsal riskler', 'Teminat mektubu ihtiyacına yönelik kefalet sigortası ve kefalet senedi; sorumluluk, nakliyat, mühendislik; yenileme ve hasar takibi.'],
    ],
    extra:
      'Şirket ağımız: Aksigorta, Anadolu Sigorta, HDI, MAPFRE, Quick, Türkiye Sigorta, Allianz, Magdeburger, Sompo, Unico, Doğa, Neova, Ray, Koru, Ankara Sigorta, Groupama, Türk Nippon.',
    cta: 'Sigorta ve teminat ihtiyaçlarınız için teklif isteyin.',
    note: 'Kefalet senedi düzenlenmesi sigortacı değerlendirmesine ve ilgili kabul koşullarına bağlıdır. Ürün, teminat ve istisnalar poliçede belirlenir.',
  },
  {
    no: '10',
    group: 'hukuk-mali',
    kicker: 'Muhasebe ve Finansal Düzen',
    name: 'XRE Mali Müşavirlik',
    headline: 'Rakamlarınız düzenli. Kararlarınız bilinçli.',
    intro:
      'Şirketlerin kuruluşundan günlük muhasebe işleyişine, beyan süreçlerinden yönetim raporlamasına kadar mali müşavirlik hizmetleri. İşletmenizin finansal verilerini düzenli, izlenebilir ve karar vermeye elverişli bir yapıya dönüştürmeyi hedefliyoruz.',
    items: [
      ['Kuruluş ve yapılandırma', 'Şirket türü ve kuruluş süreçleri, şube açılışı, ticaret sicili işlemleri ve mali yükümlülük takvimi.'],
      ['Muhasebe ve beyan', 'Defter ve kayıt düzeni, e-defter, e-fatura ve e-arşiv süreçleri; beyannameler ve dönem kapanışları.'],
      ['Bordro ve işveren süreçleri', 'Ücret bordroları, personel maliyetleri, SGK bildirimleri ve çalışan dosyalarına ilişkin mali süreçler.'],
      ['Yönetim raporları', 'Gelir-gider, cari hesap, stok, maliyet ve nakit akışı raporları; bütçe takibi ve teşvik uygunluğu değerlendirmesi.'],
    ],
    highlight: 'Günlük kayıtlarla yönetim kararları arasında düzenli bir bilgi akışı kurun.',
    cta: 'İşletmenizin muhasebe ve raporlama ihtiyacını paylaşın.',
    note: 'Mesleki hizmetler, yetkili serbest muhasebeci mali müşavirler tarafından ilgili mevzuat çerçevesinde yürütülür.',
  },
  {
    no: '11',
    group: 'hukuk-mali',
    kicker: 'Tasdik ve Vergi İncelemesi',
    name: 'XRE Yeminli Mali Müşavirlik',
    headline: 'Mali süreçlerde ayrıntılı inceleme.',
    intro:
      'İşletmelerin vergi ve mali işlemleri için yeminli mali müşavirlik, tasdik ve inceleme hizmetleri. İşlem dayanakları ve kayıt düzeni birlikte değerlendirilerek belgeli ve takip edilebilir bir çalışma yürütülür.',
    items: [
      ['Tam tasdik', 'Mevzuat kapsamındaki tam tasdik çalışmaları; kayıtların, beyanların ve dayanak belgelerin incelenmesi.'],
      ['KDV iade süreçleri', 'İade dosyası hazırlığı, belge ve hesap kontrolleri; ilgili mevzuata göre tasdik raporu ve süreç takibi.'],
      ['İstisna ve teşvik incelemesi', 'Vergi istisnaları, indirimler ve teşviklere ilişkin uygunluk ve belge düzeninin değerlendirilmesi.'],
      ['Özel amaçlı mali inceleme', 'İşlem bazlı incelemeler, vergi risklerinin değerlendirilmesi ve mali tabloların yönetim açısından analizi.'],
    ],
    highlight: 'Vergi süreçlerinizi güçlü bir belge düzeni ve uzman incelemesiyle destekleyin.',
    cta: 'Tasdik veya mali inceleme ihtiyacınız için görüşelim.',
    note: 'YMM hizmetleri yetkili yeminli mali müşavirlerce yürütülür. Bağımsız denetim ayrı yetkilendirmeye tabidir.',
  },
  {
    no: '12',
    group: 'maliyet-varlik',
    kicker: 'Alım, Satım, Konsinye ve Kiralama',
    name: 'XRE Auto',
    headline: 'Araç ihtiyacınıza ticari bir bakış.',
    intro:
      'Bireysel araç talepleri ve şirketlerin araç ihtiyaçları için alım, satım, konsinye, kiralama ve filo danışmanlığı. Kullanım amacı, bütçe ve toplam sahip olma maliyetini birlikte değerlendiriyoruz.',
    items: [
      ['Alım, satım ve ekspertiz', 'Binek ve ticari araçlarda seçenek sunumu; bağımsız ekspertiz, araç geçmişi ve belge kontrolleri, devir ve teslim koordinasyonu.'],
      ['Konsinye araç satışı', 'Aracın sahibi adına satışa sunulması; fiyatlandırma, ilan ve tanıtım, alıcı görüşmeleri ve satış takibi. Teslim ve hizmet koşulları yazılı belirlenir.'],
      ['Kiralama ve filo', 'Kısa ve uzun dönem kiralama seçenekleri; filo oluşturma, yenileme ve kullanım maliyetlerinin değerlendirilmesi.'],
      ['Takas ve kurumsal çözümler', 'Uygun araçların XRE Barter kapsamında değerlendirilmesi; sigorta ve şirket ihtiyaçlarıyla birlikte çözüm oluşturulması.'],
    ],
    highlight: 'Araç kararlarınızı kullanım ihtiyacı, nakit akışı ve maliyet açısından birlikte değerlendirin.',
    cta: 'Aradığınız veya konsinye satışa sunmak istediğiniz aracı paylaşın.',
    note: 'Araç temini, konsinye, kiralama ve ticari işlemler ilgili yetkiler ve sözleşme koşulları çerçevesinde yürütülür.',
  },
  {
    no: '13',
    group: 'teknoloji',
    kicker: 'Uluslararası Fuar ve İş Buluşmaları',
    name: 'XRE Fair',
    headline: 'İşinizi dünyayla buluşturun.',
    intro:
      'Fuar, ticari buluşma ve etkinlik organizasyonlarıyla şirketleri yeni iş ilişkilerine taşıyoruz. XRE Fair, 60 büyükelçilik ve ticari ataşeliğin katılımıyla oluşan uluslararası etkileşimi iş geliştirme odağında değerlendiriyor.',
    items: [
      ['Fuar ve etkinlik organizasyonu', 'Sektörel fuarlar, proje tanıtımları, ticari buluşmalar ve kurumsal organizasyonlar için planlama ve koordinasyon.'],
      ['Uluslararası bağlantılar', 'Büyükelçilikler, ticari ataşelikler, iş dünyası temsilcileri ve katılımcı firmalar arasında iletişim zemini.'],
      ['Şirket ve proje görünürlüğü', 'Stand planlaması, sunum, tanıtım materyalleri ve etkinlik içi marka iletişimi çalışmalarının koordinasyonu.'],
      ['Görüşmeden iş takibine', 'İkili iş görüşmeleri, potansiyel müşteri ve iş ortağı bağlantıları; etkinlik sonrasında görüşmelerin takibi.'],
    ],
    stat: ['60', 'büyükelçilik ve ticari ataşelik'],
    highlight: 'Guinness Dünya Rekorları hedefiyle, uluslararası ölçekte ses getiren buluşmalar.',
    cta: 'Firmanız için katılım ve iş birliği seçeneklerini görüşelim.',
    note: '60 temsilcilik katılımı şirketin paylaştığı bilgidir. Guinness ifadesi rekor hedefini belirtir; tescil edilmiş rekor beyanı değildir.',
  },
  {
    no: '14',
    group: 'teknoloji',
    kicker: 'Kurumsal Yazılım Hizmetleri',
    name: 'XRE Software',
    headline: 'İşinize göre tasarlanan yazılım.',
    intro:
      'Şirketinizin günlük işleyişine ve büyüme hedeflerine uygun yazılım çözümleri geliştiriyoruz. İhtiyaç analizinden tasarım ve uygulamaya, kurulumdan eğitim ve desteğe kadar süreci birlikte planlıyoruz.',
    items: [
      ['Web ve mobil çözümler', 'Kurumsal web siteleri, web ve mobil uygulamalar, e-ticaret sistemleri ve müşteri portalları için tasarım ve geliştirme.'],
      ['İş ve operasyon yazılımları', 'CRM, satış, teklif, stok, görev ve ekip yönetimi; şirketinizin çalışma biçimine uygun ekranlar ve iş akışları.'],
      ['Entegrasyon ve raporlama', 'Muhasebe, satış ve diğer iş uygulamaları arasında API bağlantıları ve veri akışı; yönetim panelleri ve raporlama ekranları.'],
      ['Kurulum, eğitim ve destek', 'Veri aktarımı, yetkilendirme, test, kullanıcı eğitimi ve devreye alma; bakım, güncelleme ve teknik destek süreçleri.'],
    ],
    highlight: 'İş süreçlerinizi düzenleyen, bilgiye erişimi kolaylaştıran bir yazılım altyapısı kurun.',
    cta: 'Yazılım ihtiyacınızı paylaşın, proje kapsamını birlikte oluşturalım.',
    note: 'Kapsam, entegrasyon, teslim takvimi, veri güvenliği, lisans ve kullanım hakları proje sözleşmesinde belirlenir.',
  },
  {
    no: '15',
    group: 'teknoloji',
    kicker: 'Kurumsal Yapay Zekâ Hizmetleri',
    name: 'XRE Yapay Zekâ',
    headline: 'Bilginizi işleyen sistemlere dönüştürün.',
    intro:
      'Şirket bilgilerini ve iş süreçlerini yapay zekâ uygulamalarıyla buluşturuyoruz. Kullanım senaryolarını, veriye erişim yetkilerini ve insan kontrolünü birlikte planlayarak günlük işlerde uygulanabilir çözümler oluşturuyoruz.',
    items: [
      ['Kurumsal yapay zekâ asistanları', 'Şirket dokümanlarına dayalı bilgi arama, soru yanıtlama ve çalışan destek sistemleri; departmana özel asistanların kurulması.'],
      ['Belge ve veri işleme', 'Belge sınıflandırma, veri çıkarma, özetleme, rapor hazırlama ve içerik üretimi; yoğun bilgi akışının düzenlenmesi.'],
      ['Akıllı süreç otomasyonu', 'Tekrarlayan görevlerin otomasyonu, talep yönlendirme, CRM ve iş uygulamalarıyla bağlantı; insan onaylı iş akışları.'],
      ['Uyarlama ve ekip eğitimi', 'Uygun çözüm seçimi, pilot uygulama, performans değerlendirmesi, kullanıcı eğitimi ve kullanım senaryolarının geliştirilmesi.'],
    ],
    highlight: 'Ekibinizin bilgiye erişmesini ve tekrar eden işleri daha verimli yürütmesini destekleyin.',
    cta: 'Yapay zekâ ile geliştirmek istediğiniz süreci birlikte değerlendirelim.',
    note: 'Veri erişimi ve güvenlik koşulları proje özelinde belirlenir. Kritik çıktılar insan kontrolünden geçirilir.',
  },
  {
    no: '16',
    group: 'teknoloji',
    kicker: 'Hizmet Sunumu ve Sistem Satışı',
    name: 'XRE Yapay Zekâ Call Center',
    headline: 'Her görüşmeyi takip edilebilir bir sürece taşıyın.',
    intro:
      'Şirketler için yapay zekâ destekli çağrı merkezi hizmetleri ve sistem satışı. Gelen ve giden aramaları; müşteri karşılama, satış desteği, randevu oluşturma ve CRM takibiyle birlikte kurguluyoruz.',
    items: [
      ['Gelen çağrı yönetimi', 'Müşteri karşılama, sık sorulan sorular, talep sınıflandırma ve gerekli durumlarda ilgili çalışana aktarım.'],
      ['Giden arama ve satış desteği', 'Uygun izinler çerçevesinde tanıtım, ön görüşme, müşteri ihtiyaç analizi, geri arama ve teklif takibi.'],
      ['Randevu ve CRM bağlantısı', 'Takvim uygunluğuna göre randevu oluşturma, görüşme özeti, müşteri kaydı ve sonraki görevlerin CRM’e aktarılması.'],
      ['Hizmet veya sistem satın alma', 'Yönetilen çağrı merkezi hizmeti ya da şirkete özel kurulum ve lisanslama; senaryo hazırlığı, eğitim ve teknik destek.'],
    ],
    highlight: 'Çağrıyı, müşteri bilgisini ve sonraki adımı aynı çalışma düzeninde birleştirin.',
    cta: 'İşinize uygun çağrı senaryosu ve sistem gösterimi isteyin.',
    note: 'Aramalar ve kayıtlar ilgili izin, KVKK ve ticari ileti kurallarıyla yürütülür. Kapasite ve entegrasyonlar teklif kapsamında belirlenir.',
  },
  {
    no: '17',
    group: 'teknoloji',
    kicker: 'İçerik, Reklam ve Müşteri Kazanımı',
    name: 'XRE Sosyal Medya & Reklam',
    headline: 'Markanız görünsün. Mesajınız anlaşılsın.',
    intro:
      'Şirketinizin sosyal medya iletişimini ve dijital reklamlarını tek bir plan içinde yönetiyoruz. Marka dili, içerik, kampanya ve potansiyel müşteri takibini ölçülebilir hedefler etrafında bir araya getiriyoruz.',
    items: [
      ['Hesap ve içerik yönetimi', 'Instagram, Facebook, LinkedIn ve ihtiyaca uygun diğer kanallar için içerik takvimi, metin ve yayın yönetimi.'],
      ['Görsel ve video üretimi', 'Grafik tasarım, kurumsal tanıtım, ürün ve proje içerikleri, video, Reels ve kampanya görsellerinin hazırlanması.'],
      ['Meta ve Google reklamları', 'Hedef kitle, reklam metni, görsel, kampanya kurulumu ve bütçe takibi; başvuru ve dönüşüm odaklı çalışmalar.'],
      ['Ölçüm ve müşteri takibi', 'Başvuru maliyeti, dönüşüm ve kampanya raporları; potansiyel müşterilerin satış ekibine ve CRM’e aktarılması.'],
    ],
    highlight: 'Dijital görünürlüğünüzü, satış sürecinizle bağlantılı ve ölçülebilir bir yapıda yönetin.',
    cta: 'Markanız için içerik ve reklam planı hazırlayalım.',
    note: 'Reklam bütçesi ve hizmet bedeli ayrı tanımlanır. Sonuçlar hedef kitle, bütçe, teklif ve satış sürecine göre değişir.',
  },
  {
    no: '18',
    group: 'teknoloji',
    kicker: 'Mimarlık ve Mekân Tasarımı',
    name: 'XRE Architecture',
    headline: 'Fikirden kullanılan mekâna.',
    intro:
      'Konut, ofis, mağaza, otel ve ticari projeler için mimarlık ve iç mekân tasarımı. Kullanıcı deneyimini, işlevi, estetiği ve uygulama bütçesini birlikte ele alan proje yaklaşımı.',
    items: [
      ['Konsept ve fizibilite', 'İhtiyaç programı, yerleşim alternatifleri, mekân kullanımı ve başlangıç bütçesi üzerinden tasarım yaklaşımı.'],
      ['Mimari ve iç mimari proje', 'Plan, cephe, malzeme, aydınlatma ve iç mekân çözümleri; ilgili disiplinlerle proje koordinasyonu.'],
      ['Görselleştirme', 'Üç boyutlu modelleme, mimari görselleştirme ve sunumlarla tasarımın uygulama öncesinde değerlendirilmesi.'],
      ['Uygulama koordinasyonu', 'Detay projeleri, imalat ve malzeme seçimleri; talep kapsamına göre keşif, iş programı ve saha takibi.'],
    ],
    highlight: 'Mekânınızı markanızın, kullanıcılarınızın ve işletme hedeflerinizin bir parçası olarak tasarlayın.',
    cta: 'Projenizin konumunu ve ihtiyaçlarını birlikte değerlendirelim.',
    note: 'Proje, imza ve mesleki sorumluluk gerektiren hizmetler yetkili mimar ve ilgili uzmanlar tarafından yürütülür.',
  },
  {
    no: '19',
    group: 'teknoloji',
    kicker: 'Planlama ve Arazi Geliştirme',
    name: 'XRE Şehir Planlama',
    headline: 'Arazinin potansiyelini planla ortaya koyun.',
    intro:
      'Arsa ve arazilerin mevcut plan kararlarıyla birlikte değerlendirilmesi; planlama, kentsel gelişim ve proje hazırlık süreçlerinin koordinasyonu. Her çalışma, taşınmazın konumu ve ilgili idarenin koşulları üzerinden ele alınır.',
    items: [
      ['Mevcut durum analizi', 'İmar planı ve plan notları, kullanım kararları, ulaşım, altyapı ve çevresel koşulların birlikte değerlendirilmesi.'],
      ['Planlama çalışmaları', 'İlgili ölçekte plan ve plan değişikliği çalışmalarının hazırlanması; teknik ve kurumsal süreçlerin koordinasyonu.'],
      ['Geliştirme senaryoları', 'Arazi kullanım alternatifleri, etaplama, yoğunluk, donatı ve proje ihtiyaçlarına yönelik senaryo çalışmaları.'],
      ['Kurum ve süreç takibi', 'İlgili idare görüşleri, başvuru dosyaları, teknik çalışmalar ve planlama takviminin düzenli izlenmesi.'],
    ],
    highlight: 'Arazi kararlarınızı plan, altyapı ve kullanım koşullarını birlikte görerek verin.',
    cta: 'Parsel bilgilerinizi paylaşın, planlama ihtiyacını değerlendirelim.',
    note: 'Planlama hizmetleri yetkili meslek mensuplarınca yürütülür. İmar, plan değişikliği veya idari onay garantisi verilmez.',
  },
  {
    no: '20',
    group: 'maliyet-varlik',
    kicker: 'Borç Yapılandırma ve Takas',
    name: 'XRE Barter',
    headline: 'Varlıklarınızdan yeni çözüm seçenekleri üretin.',
    intro:
      'Nakit akışı zorlanan şirketler ile varlıklarını takas yoluyla değerlendirmek isteyen kişi ve kurumlar için barter çözümleri. Ticari borç, alacak ve varlıklar birlikte incelenerek tarafların kabul edeceği işlem modelleri oluşturulur.',
    items: [
      ['Ticari borç yapılandırma', 'Tedarikçi, mal ve hizmet borçlarının analizi; ödeme kapasitesi, vade ve varlıkla kapama seçeneklerinin çalışılması.'],
      ['Takas ve varlık değerlendirme', 'Gayrimenkul, araç, iş makinesi, stok, ürün ve uygun hizmetlerin karşılıklı değerleme ve eşleştirme yoluyla ele alınması.'],
      ['Alacaklıyla çözüm geliştirme', 'Tam veya kısmi kapama, nakit ve varlık bileşimi, ilgili temlik ve mahsup seçenekleri için müzakere koordinasyonu.'],
      ['Hukuki ve ticari koordinasyon', 'Mülkiyet, takyidat, değerleme, sözleşme, devir ve ödeme takibi; ihtiyaç hâlinde ilgili hukuk ve mali uzmanlarla çalışma.'],
    ],
    highlight: 'Satışı bekleyen varlıkları, borç ve ticari ihtiyaçların çözümünde değerlendirin.',
    cta: 'Borç, alacak veya takasa konu varlığınızı paylaşın.',
    note: 'İşlemler inceleme, değerleme ve taraf mutabakatına bağlıdır. Konkordato ve iflasta ilgili makamların yetki ve izinleri gözetilir.',
  },
  {
    no: '21',
    group: 'hukuk-mali',
    kicker: 'Ulusal ve Uluslararası Sınai Mülkiyet',
    name: 'XRE Patent',
    headline: 'Türkiye’den dünyaya haklarınızı koruyun.',
    intro:
      'Marka, patent, faydalı model ve tasarım haklarınızı Türkiye’de ve hedef dış pazarlarda birlikte planlıyoruz. Ön araştırmadan başvuruya, tescil takibinden yenilemelere kadar ulusal ve uluslararası süreçleri koordine ediyoruz.',
    items: [
      ['Ulusal başvuru ve koruma', 'Türkiye’de marka, patent, faydalı model ve tasarım için araştırma, başvuru hazırlığı, inceleme ve tescil süreçlerinin takibi.'],
      ['Uluslararası marka ve tasarım', 'Hedef ülkelerin belirlenmesi; Madrid ve Lahey sistemleri veya doğrudan ülke başvuruları için uygun yolun ve takvimin planlanması.'],
      ['Uluslararası patent süreçleri', 'Buluşun hedef pazarlarına göre yurt dışı başvuru stratejisi; ülke ve bölgesel başvuru süreçlerinin ilgili vekillerle koordinasyonu.'],
      ['İzleme, yenileme ve hak takibi', 'Ulusal ve uluslararası hakların izlenmesi; itiraz, yenileme, lisans ve devir işlemleri, hukuki uyuşmazlıklarda avukatlarla koordinasyon.'],
    ],
    highlight: 'Markanızı ve yeniliklerinizi faaliyet gösterdiğiniz pazarlara uygun bir koruma planıyla yönetin.',
    cta: 'Türkiye ve hedef ülkeleriniz için koruma planını birlikte hazırlayalım.',
    note: 'İşlemler ilgili sicillere kayıtlı vekiller ve gerektiğinde yerel uzmanlarla yürütülür. Koruma ve tescil şartları ülkeye göre değişir.',
  },
  {
    no: '22',
    group: 'gayrimenkul',
    kicker: 'Uluslararası Ağ Geliştirme',
    name: 'XRE Master Franchise',
    headline: 'Bir bölgenin büyümesine liderlik edin.',
    intro:
      'Belirlenen ülke veya bölgede XRE markasının yapılanmasını geliştirmek isteyen girişimci ve iş ortakları için master franchise modeli. Bölgesel büyüme, yerel operasyon ve alt franchise ağı birlikte planlanır.',
    items: [
      ['Ülke ve bölge değerlendirmesi', 'Pazar büyüklüğü, rekabet, yerel mevzuat, girişimci profili ve gelişim fırsatlarına göre bölgesel iş planı.'],
      ['Ağ ve ekip kurulumu', 'Yerel yönetim yapısı, franchise aday kazanımı, ofis açılış planları ve ekip gelişimi için çalışma modeli.'],
      ['Marka ve operasyon standardı', 'Kurumsal kimlik, eğitim, teknoloji, kalite ve performans kriterlerinin yerel ihtiyaçlarla birlikte uygulanması.'],
      ['Sözleşme ve büyüme planı', 'Yetki alanı, hedefler, alt franchise hakları, destek kapsamı, raporlama ve mali koşulların açık biçimde tanımlanması.'],
    ],
    highlight: 'XRE’nin ülke ve bölge yapılanmasında uzun vadeli bir iş ortaklığı geliştirin.',
    cta: 'Master franchise için hedef ülke veya bölgenizi paylaşın.',
    note: 'Master franchise hakları ve varsa münhasırlık yalnızca imzalanan sözleşmenin kapsamıyla sınırlıdır.',
  },
  {
    no: '23',
    group: 'maliyet-varlik',
    kicker: 'Kurumsal Varlık Danışmanlığı',
    name: 'XRE Varlık Yönetimi',
    headline: 'Varlıklarınızı bütüncül bir bakışla yönetin.',
    intro:
      'Şirketlerin gayrimenkul, araç, makine, ekipman, stok ve ticari alacaklarını birlikte değerlendiren varlık yönetimi danışmanlığı. Varlıkların mevcut durumunu, kullanımını ve işletmeye katkısını görünür hâle getirerek değerlendirme seçenekleri oluşturuyoruz.',
    items: [
      ['Envanter ve durum analizi', 'Varlık listesi, mülkiyet ve kullanım belgeleri, sözleşmeler, gelir-gider bilgileri ve yükümlülüklerin tek bir çalışma düzeninde toplanması.'],
      ['Performans ve değer analizi', 'Kullanım oranı, kira geliri, bakım ve işletme maliyetlerinin incelenmesi; ihtiyaç hâlinde bağımsız değerleme koordinasyonu.'],
      ['Değerlendirme ve nakde dönüş', 'Atıl varlıklarda satış, kiralama, yeniden kullanım ve barter seçenekleri; işletme ihtiyacına göre önceliklendirme ve uygulama takibi.'],
      ['Operasyon ve alacak takibi', 'Kira, bakım, sigorta ve yenileme takvimleri; ticari alacaklarda vade ve tahsilat takibi, ilgili uzmanlarla süreç koordinasyonu.'],
    ],
    highlight: 'Şirketinizin sahip olduklarını, maliyetlerini ve değerlendirme seçeneklerini aynı tabloda görün.',
    cta: 'Varlık listenizi paylaşın, yönetim planını birlikte oluşturalım.',
    note: 'Düzenlemeye tabi alacak devralma ve sermaye piyasası portföy yönetimi işlemleri, yalnızca gerekli yetkiye sahip kuruluşlarca yürütülür.',
  },
  {
    no: '24',
    group: 'hukuk-mali',
    kicker: 'Nakit Akışı, Bütçe ve Finansman',
    name: 'XRE Finansal Danışmanlık',
    headline: 'Finansal kararları verilerle planlayın.',
    intro:
      'Şirketlerin nakit akışını, finansman ihtiyacını, borç ödeme kapasitesini ve büyüme planlarını birlikte ele alıyoruz. Mevcut mali tabloyu anlaşılır raporlara dönüştürerek yönetimin uygulanabilir kararlar almasına destek oluyoruz.',
    items: [
      ['Nakit akışı ve bütçe', 'Haftalık ve aylık nakit akışı, tahsilat-ödeme takvimi, işletme sermayesi ihtiyacı ve bütçe gerçekleşmelerinin takibi.'],
      ['Finansman hazırlığı', 'Finansman ihtiyacının hesaplanması, başvuru dosyası ve iş planı hazırlığı; tekliflerin vade, toplam maliyet ve teminat açısından karşılaştırılması.'],
      ['Borç ve ödeme planlaması', 'Borçların vade, maliyet ve teminat yapısının analizi; ödeme kapasitesine uygun senaryolar ve yapılandırma görüşmelerine hazırlık.'],
      ['Kârlılık ve büyüme analizi', 'Ürün, proje ve faaliyet bazında kârlılık, başabaş noktası ve yatırım bütçesi; büyüme kararları için finansal senaryo çalışmaları.'],
    ],
    highlight: 'Nakit ihtiyacını önceden görün; borç, maliyet ve büyüme kararlarını birlikte değerlendirin.',
    cta: 'Finansal durumunuzu birlikte değerlendirelim, yol haritasını hazırlayalım.',
    note: 'Hizmet kurumsal finansal planlama kapsamındadır. Finansman onayı veya getiri taahhüdü verilmez; sermaye piyasası yatırım danışmanlığı ayrı yetkiye tabidir.',
  },
  {
    no: '25',
    group: 'gayrimenkul',
    kicker: 'İş Adresi ve Ofis Destek Hizmetleri',
    name: 'XRE Sanal Ofis',
    headline: 'Kurumsal adres. Esnek çalışma.',
    intro:
      'Girişimciler, uzaktan çalışan ekipler ve şirketler için sanal ofis çözümleri. İş adresi, posta ve kargo yönetimi, çağrı karşılama ve toplantı alanı ihtiyaçlarını şirketinizin çalışma düzenine uygun bir hizmet kapsamında bir araya getiriyoruz.',
    items: [
      ['İş adresi kullanımı', 'Şirket kuruluşu veya adres değişikliği için uygunluk değerlendirmesi; sözleşme kapsamında iş adresi kullanımı ve ilgili süreçlerin koordinasyonu.'],
      ['Posta ve kargo yönetimi', 'Gelen posta ve kargoların kabulü, kayıt altına alınması ve bildirilmesi; yazılı yetki ve hizmet kapsamına göre teslim veya yönlendirme.'],
      ['Çağrı karşılama ve iletişim', 'Paket kapsamında şirket adına çağrı karşılama, mesaj alma, ilgili kişiye yönlendirme ve müşteri taleplerinin düzenli aktarılması.'],
      ['Toplantı ve çalışma alanları', 'İhtiyaç duyulan günlerde toplantı odası veya çalışma alanı kullanımı; rezervasyon, misafir karşılama ve uygun ofis destek hizmetleri.'],
    ],
    highlight: 'İşinizin adres, iletişim ve toplantı ihtiyaçlarını tek bir hizmet düzeninde yönetin.',
    cta: 'Sanal ofis ihtiyacınızı paylaşın, size uygun hizmet kapsamını oluşturalım.',
    note: 'Adres kullanım uygunluğu faaliyet türüne ve ilgili kurum koşullarına göre değerlendirilir. Lokasyon, kullanım süresi, ücret ve ek hizmetler sözleşmede belirlenir.',
  },
];

export const contact = {
  phone: '444 24 53',
  phoneHref: 'tel:+904442453',
  web: 'xre.com.tr',
  webHref: 'https://xre.com.tr',
  city: 'Ankara / Beştepe',
};
